package com.osp.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SPaymentFee generated by hbm2java
 */
@Entity
@Table(name = "SIMA_CUST_SERVICE")
public class CustService implements java.io.Serializable {

    @Id
    @SequenceGenerator(name = "SIMA_CUST_SERVICE_SEQ", sequenceName = "SIMA_CUST_SERVICE_SEQ", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIMA_CUST_SERVICE_SEQ")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CUSTOMER_ID")
    private Customer customer;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PACKAGE_ID")
    private ConfPackage confPackage;

    @Column(name = "STATUS", nullable = false, length = 1)
    private Short status;

    @Column(name = "EXPIRED_DATE")
    private Date expiredDate;

    public CustService() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public Date getExpiredDate() {
        return expiredDate;
    }

    public void setExpiredDate(Date expiredDate) {
        this.expiredDate = expiredDate;
    }

    public ConfPackage getConfPackage() {
        return confPackage;
    }

    public void setConfPackage(ConfPackage confPackage) {
        this.confPackage = confPackage;
    }

}
